# Census Data Retrieval Tool Configuration

# API Configuration
api:
  key: ${CENSUS_API_KEY}  # This will be loaded from the .env file

# Input Configuration
input:
  file_path: "./data/input/census_stats_config.json"

# Output Configuration
output:
  directory: "./data/processed"
  file_naming: "census_data_{city}_{year}.md"

# Error Handling and Retry Settings for API Requests
error_handling:
  max_retries: 3
  retry_delay: 5  # seconds

# Performance Configuration
performance:
  concurrent_requests: 5  # Number of concurrent API requests
